sudo: required
language: python
matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: nightly
    - python: pypy
    - language: generic
      os: osx
    - language: generic
      os: osx
      env: PY3=3

install: .ci/travis.sh
script: cd tests && python$PY3 -m pytest

notifications:
    email:
        on_success: change
        on_failure: change
